export { ReactComponent as LogoImage } from './logo.svg'
export { ReactComponent as CheckIcon } from './check.svg'
export { ReactComponent as StarIcon } from './star.svg'
export { ReactComponent as StarFullIcon } from './star-full.svg'
export { ReactComponent as SearchIcon } from './search.svg'
export { ReactComponent as PlaneIcon } from './plane.svg'
export { ReactComponent as EndIcon } from './end.svg'
export { ReactComponent as RefreshIcon } from './refresh.svg'
export { ReactComponent as HeartIcon } from './heart.svg'
export { ReactComponent as CommentIcon } from './comment.svg'
export { ReactComponent as UserIcon } from './user.svg'

export { ReactComponent as CaretDownIcon } from './caret-down.svg'
export { ReactComponent as CircleCheckIcon } from './circle-check.svg'
export { ReactComponent as EyeIcon } from './eye.svg'
export { ReactComponent as EyeSlashIcon } from './eye-slash.svg'
